server:
  ip: localhost
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/qing?serverTimezone=GMT%2b8
    username: root
    password: 12345
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: D:/files/
    path2: D:/files/temp/tire/
    detect1Path: D:/files/detect1/
    detect2Path: D:/files/detect2/
    recognisePath: D:/files/recognise/
#    path: /home/files/

#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyid: LTAI5tQZXNdiGawZkVJZqJNx
      keysecret: 9TOsH1mCy9KOjpYZx1vT54HWFF3AGX
      bucketname: ahpu-music